@----------------------------------------------------------
@ Labo ARO2 - Micro architecture FETCH
@ HEIG-VD / Institut REDS
@ Prof. C. Andrés Pena, R. Mosqueron
@ Ass. Flavio Capitao, Anthony Convers, 
@      Alexandre Malki, Gaetan Matthey
@----------------------------------------------------------
@	Auteur	:	
@	Date	:
@----------------------------------------------------------
@
@	Description de votre programme
@
@----------------------------------------------------------


MOV r1, #2
MOV r3, #25
ADD r2, r1, r3
MOV r1, #12
ADD r0, r1, r2
MOV r3, r0
