@----------------------------------------------------------
@ Labo ARO2 - Micro architecture FETCH
@ HEIG-VD / Institut REDS
@ Prof. C. Andrés Pena, R. Mosqueron
@ Ass. Flavio Capitao, Anthony Convers, 
@      Alexandre Malki, Gaetan Matthey
@----------------------------------------------------------
@	Auteur	:	
@	Date	:
@----------------------------------------------------------
@
@	Description de votre programme
@
@----------------------------------------------------------

MOV	r0, #27
MOV	r2, #4
MOV	r3, #67	
MOV	r1, r3
MOV r0, r2
MOV r1, #0xAC
